name: Tests
on: [pull_request, push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install and lint
        uses: actions/setup-node@v1
        run: |
          npm install
          npm run lint

  unit-test:
    runs-on: actions/setup-node@v1
    steps:
    - name: Install
      run: npm install

    - name: Unit test
      run: npm run test:unit

  integration-test:
    runs-on: actions/setup-node@v1
    steps:
      - name: Install
        run: npm install

      - name: Integration test
        run: npm run test:e2e -- --headless

  build:
    runs-on: actions/setup-node@v1
    steps:
      - name: Install
        run: npm install

      - name: Build
        run: npm run build
