name: Deploy on Github Pages
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DEPLOY_BRANCH: gh-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'

      - name: Install
        run: npm install

      # Generates `dist/` directory
      - name: Build
        run: npm run build

      # Use of SSH Key stored as secret instead of auto-created GITHUB_TOKEN secret
      # Because of this issue on public repo:
      # https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/td-p/26869/highlight/true/page/2
      - name: Add SSH key
        run: |
          mkdir "/$HOME/.ssh"
          ssh-keyscan -t rsa github.com > "/$HOME/.ssh/known_hosts"
          echo "${{ secrets.GIT_DEPLOY_KEY }}" > "/$HOME/.ssh/id_rsa"
          chmod 400 "/$HOME/.ssh/id_rsa"

      # Push to the Github Pages branch
      - name: Deploy to Github Pages
        run: |
          cd dist
          git init
          git remote add deploy "git@github.com:$GITHUB_REPOSITORY"
          git checkout --orphan "$DEPLOY_BRANCH"
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add .
          git commit -m "Automated deployment to GitHub Pages"
          git push deploy "$DEPLOY_BRANCH" --force

