name: Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DEPLOY_BRANCH: gh-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'

      - name: Install
        run: npm install

      # Generates `dist/` directory
      - name: Build
        run: npm run build

      # Push to the Github Pages branch
      - name: Deploy to Github Pages
        run: |
          cd dist
          git init
          git remote add deploy "$GITHUB_REPOSITORY"
          git checkout "$DEPLOY_BRANCH"
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add .
          git commit - m "Automated deployment to GitHub Pages"
          git push deploy "$DEPLOY_BRANCH" --force

