name: Tests
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'

      - name: Install
        run: npm install

      - name: Lint
        run: npm run lint

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'

      - name: Install
        run: npm install

      - name: Unit test
        run: npm run test:unit


  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'

      - name: Install
        run: npm install

      - name: Integration test
        run: npm run test:e2e -- --headless

      # Cypress only saves screenshots if the test fails
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: screenshots
          path: tests/e2e/screenshots/

      - uses: actions/upload-artifact@v1
        # if: failure()
        with:
          name: videos
          path: tests/e2e/videos/

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'

      - name: Install
        run: npm install

      - name: Build
        run: npm run build
